### ISSUE TITLE
No implementation found  (io.github.kihyun1998/cert_installer)

### ISSUE THREAD

**Issue by Zhaodaidai** [kihyun1998/x509_cert_store#1]
Unhandled Exception: MissingPluginException(No implementation found for method addCertificate on channel io.github.kihyun1998/cert_installer)

**Comment by kihyun1998** [comment]
checking what happens..

**Comment by kihyun1998** [comment]
What version of the plugin are you using?

**Comment by Zhaodaidai** [comment]
> 您使用的插件是哪个版本？

x509_cert_store: ^0.9.5

**Comment by kihyun1998** [comment]
Can you tell me how you called it?

**Comment by Zhaodaidai** [comment]
> 你能告诉我你是怎么称呼它的吗？

![%% A1Q$U4UP0$DE9UB7KCYD](https://github.com/kihyun1998/x509_cert_store/assets/71388480/f1df2f00-4a1e-41bb-9008-ee3223a5625d)
like this

**Comment by kihyun1998** [comment]
Are you sure you are using it on a Windows operating system? This package still only provides Windows.

**Comment by kihyun1998** [comment]
Are you in MacOS?

**Comment by Zhaodaidai** [comment]
SORRY, my mistake

**Comment by kihyun1998** [comment]
Oh! How did you solve it?
